apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-operator
    app.kubernetes.io/part-of: openshift-node-feature-discovery
  name: openshift-cluster-nfd-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: openshift-cluster-nfd-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: openshift-cluster-nfd-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-operator@sha256:00d8d8d8dc810c9e7db252d87d2b4e4b69d3142c6486499803c0bf69fa5dc3c2
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
