apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: openshift-cluster-nfd-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-operator@sha256:baefd9fda721b38141fdb750c3684b6109c387bb8fba925956418c35901c2f59
        name: container-image
        resources: {}
status: {}
