apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: openshift-cluster-nfd-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-operator@sha256:78d5dc6193a4df9f76b3a3ba518f5be6a1252de0507b4e875c287e42b909c6cb
        name: container-image
        resources: {}
status: {}
