apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: openshift-cluster-nfd-operator
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-operator@sha256:bf417201611d0b52879028dbe963c7ca7560b304c33de75496e6af6d6d9a4f68
        name: container-image
        resources: {}
status: {}
