apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-operator
    app.kubernetes.io/part-of: openshift-node-feature-discovery
  name: openshift-cluster-nfd-opeh1sp
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: openshift-cluster-nfd-operator
    weight: 100
status: {}
