apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-operator-olld
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-operator-olld
    app.kubernetes.io/part-of: openshift-node-feature-discovery
  name: openshift-cluster-nfd-opeqe1n
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: openshift-cluster-nfd-operator-olld
    weight: 100
status: {}
