apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: openshift-node-feature-discovery
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-node-feature-discovery@sha256:47e290893977a1b124bd3f4bc7e4c600234db2734712865c9d61a8d19aea4d45
        name: container-image
        resources: {}
status: {}
