apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-bundle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-bundle
    app.kubernetes.io/part-of: openshift-node-feature-discovery
  name: openshift-cluster-nfd-bundle
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: openshift-cluster-nfd-bundle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: openshift-cluster-nfd-bundle
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-bundle@sha256:769a50d20755919decda93ad6be43b17b609bd97291a5e319d163758254c6feb
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
