apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: openshift-cluster-nfd-operator-olld
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: openshift-cluster-nfd-operator-olld
    app.kubernetes.io/part-of: openshift-node-feature-discovery
  name: openshift-cluster-nfd-operator-olld
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: openshift-cluster-nfd-operator-olld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: openshift-cluster-nfd-operator-olld
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-gps-cprocter-tenant/openshift-node-feature-discovery/openshift-cluster-nfd-operator-olld@sha256:e2a6cfdfe921a7f20952ea957d716fd6f590c44b2024abc6f7e049a46dac1afd
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
